service: telegram-bot
provider:
  name: aws
  runtime: nodejs12.x
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
  echoBot:
    handler: handler.echoBot
    events:
      - http:
          path: echo
          method: post
plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-typescript
  - serverless-offline
